# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  name: default

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: WhiteSource@21
  inputs:
    cwd: '$(System.DefaultWorkingDirectory)'
    projectName: 'Mend_Bolt_Project'


- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'


- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(8b0bc9d4-37d1-4f2b-ac0e-ab7d60ffe23e)'
    command: 'test'
    projects: '**/TestProject1.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: PublishCodeCoverageResults@2
  inputs:
    summaryFileLocation: '$(Build.SourcesDirectory)/**/MyCoverage/coverage.cobertura.xml'
    pathToSources: '**/TestProject1.csproj'




