name: PipelineWorkflow

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
    build:
        name: Azure Pipeline
        runs-on: default
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/balakrishnan7080/AgileProject
            azure-pipeline-name: 'first-organization-for-devops.DotNetRepo'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}